export const movie = {
    adult: false,
    backdrop_path: "/9DYFYhmbXRGsMhfUgXM3VSP9uLX.jpg",
    belongs_to_collection: {
      id: 313086,
      name: "The Conjuring Collection",
      poster_path: "/z5VKhNSQKQyxm0co68HAkCqHnmX.jpg",
      backdrop_path: "/kHZaX0vuhZdbuq0WKU3BpA9WIQ0.jpg",
    },
    budget: 55000000,
    genres: [{ id: 27, name: "Horror" }],
    homepage: "http://www.theconjuringmovie.com",
    id: 1038392,
    imdb_id: "tt22898462",
    origin_country: ["US"],
    original_language: "en",
    original_title: "The Conjuring: Last Rites",
    overview:
      "Paranormal investigators Ed and Lorraine Warren take on one last terrifying case involving mysterious entities they must confront.",
    popularity: 650.5492,
    poster_path: "/gXMnx7C3cufzBHPZynWZLUHOMOT.jpg",
    production_companies: [
      { id: 12, name: "New Line Cinema", logo_path: "/2ycs64eqV5rqKYHyQK0GVoKGvfX.png", origin_country: "US" },
      { id: 76907, name: "Atomic Monster", logo_path: "/ygMQtjsKX7BZkCQhQZY82lgnCUO.png", origin_country: "US" },
      { id: 11565, name: "The Safran Company", logo_path: "/odU3l6csuBmXUrzFm6araUgEUHQ.png", origin_country: "US" },
      { id: 216687, name: "Domain Entertainment", logo_path: "/kKVYqekveOvLK1IgqdJojLjQvtu.png", origin_country: "US" },
    ],
    production_countries: [{ iso_3166_1: "US", name: "United States of America" }],
    release_date: "2025-09-03",
    revenue: 467157072,
    runtime: 135,
    spoken_languages: [{ english_name: "English", iso_639_1: "en", name: "English" }],
    status: "Released",
    tagline: "The case that ended it all.",
    title: "The Conjuring: Last Rites",
    video: false,
    vote_average: 6.9,
    vote_count: 839,
  };